#!/dis/sh.dis
# emu sh initialisation here
load std

home=/usr/^"{cat /dev/user}
mount -ac {mntgen} /n
if {~ $emuhost MacOSX}{
	trfs '#U*' /n/local >[2] /dev/null
	ghome=`{echo 'echo $HOME' | os sh}
	lhome=/n/local/^$ghome^/acme-home
}{~ $emuhost Linux}{
	trfs '#U*' /n/local >[2] /dev/null
	ghome=`{echo 'echo $HOME' | os sh}
	lhome=/n/local/^$ghome^/acme-home
}{~ $emuhost Nt}{
	for i in C D {  # add more drive letters to suit
		trfs '#U' ^ $i ^ ':/' /n/$i >[2] /dev/null
	}
	appdata=`{os cmd /c 'echo %APPDATA%' |tr -d ''| sed -n '
s/ /␣/g
s/\\/\//g
s/^([A-Z]):/\/n\/\1/p'}
	lhome=$appdata^/acme-home
}{ else
	lhome=$home
}

if {ftest -d $lhome} {} {cp -r /usr/inferno $lhome}

mount -a {mntgen} /usr
{bind -c $lhome $home; cd $home} || {bind -c /usr/inferno $home; cd $home}
mkdir -p $home/tmp && bind -bc $home/tmp /tmp
