#!/dis/sh.dis
# emu sh initialisation here
load std

user="{cat /dev/user}
if {! ~ $user inferno}{
	bind /usr/inferno /usr/$user
}
if {ftest -d /usr/$user}{
	home=/usr/$user
}{
	home=/
}
# load $home/lib/profile
cd $home 
