</mkconfig

TARG=\
	adsr.dis\
	delay.dis\
#	delayl.dis\
	fm.dis\
	instrument.dis\
#	jettabl.dis\
	lfo.dis\
	master.dis\
	mixer.dis\
	onepole.dis\
	onezero.dis\
#	polezero.dis\
	poly.dis\
	sequencer.dis\
#	twopole.dis\
#	twozero.dis\
	waveloop.dis\
	exprs.dis\
	proxy.dis\
	midi2skini.dis\
	phase.dis\

MODULES=\
	instrument.m\
	exprs.m\
	
SYSMODULES=\
	math.m\

DISBIN=/dis/synth
</mkfiles/mkdis
