<../mkconfig

LIB=libtk.a

OFILES=\
	ebind.$O\
	grids.$O\
	image.$O\
	packr.$O\
	panel.$O\
	parse.$O\
	utils.$O\
	windw.$O\
	xdata.$O\

HFILES=\
	../include/tk.h\
	../include/draw.h\

default:V:	all

<mkfile-std
<../mksyslib

ebind.$O:		../include/interp.h
windw.$O:	canvs.h textw.h
