<../../mkconfig

LIB=libmp.a
FILES=\
	mpaux\
	mpfmt\
	strtomp\
	mptobe\
	mptole\
	betomp\
	letomp\
	mpadd\
	mpsub\
	mpcmp\
	mpfactorial\
	mpmul\
	mpleft\
	mpright\
	mpvecadd\
	mpvecsub\
	mpvecdigmuladd\
	mpveccmp\
	mpdigdiv\
	mpdiv\
	mpexp\
	mpmod\
	mpextendedgcd\
	mpinvert\
	mprand\
	crt\
	mptoi\
	mptoui\
	mptov\
	mptouv\

OFILES=${FILES:%=%.$O}
# cull things in the per-machine directories from this list
#OFILES=	`{$SHELLNAME ./reduce-$SHELLTYPE $O $TARGMODEL-$OBJTYPE $ALLOFILES }

HFILES=\
	../../$OBJDIR/include/lib9.h\
	../../include/mp.h\
	dat.h\

CFILES=${FILES:%=%.c}


UPDATE=mkfile\
	$HFILES\
	$CFILES\

<../../mksyslib
