</mkconfig

TARG=\
	mapred.dis\
	adder.dis\
	grep.dis\
	sort.dis\
	tokener.dis\
	wordcount.dis\
	identity.dis\
	uniq.dis\
	lineread.dis\
	reduce.dis\
	filter.dis\

MODULES=\
	mapred.m\

SYSMODULES=\
	bufio.m\

DISBIN=$ROOT/dis/mr


<$ROOT/mkfiles/mkdis
